CREATE DATABASE SQLSTARTER;
USE SQLSTARTER;
CREATE TABLE USER(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
gender ENUM('MALE','FEMALE','OTHER'),
date_of_birth DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM USER;
RENAME TABLE USER TO PROGRAMMERS;
SELECT name FROM PROGRAMMERS;
RENAME TABLE PROGRAMMERS TO USERS;
ALTER TABLE USERS ADD COLUMN is_active BOOLEAN DEFAULT true;
select * from users;
ALTER TABLE USERS DROP COLUMN is_active;
select * from users;
ALTER TABLE USERS MODIFY COLUMN name VARCHAR(150);
ALTER TABLE USERS MODIFY COLUMN email VARCHAR(100) AFTER id;
ALTER TABLE USERS MODIFY COLUMN date_of_birth DATE FIRST;
select * from users;
